name: jalloc ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        arch: [ x86_64, arm64 ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.29.0'

      - name: Configure Project
        run: |
          mkdir build
          cd build
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-march=native"
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-arch arm64 -mtune=native"
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/arch:AVX2"  # Example for AVX2 on Windows
          fi

      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure
